#ifndef _ELOG_CFG_H_
#define _ELOG_CFG_H_

#define ELOG_OUTPUT_ENABLE
#define ELOG_OUTPUT_LVL ELOG_LVL_VERBOSE
#define ELOG_LINE_BUF_SIZE 1024
#define ELOG_LINE_NUM_MAX_LEN 5
#define ELOG_FILTER_TAG_MAX_LEN 30
#define ELOG_FILTER_KW_MAX_LEN 16
#define ELOG_FILTER_TAG_LVL_MAX_NUM 8
#define ELOG_NEWLINE_SIGN "\n"

#endif
